version: '3.8'

services:
  web:
    build: .  # Use the Dockerfile in the current directory
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html  # Mount the app directory
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent volume for MySQL data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize database with SQL script

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db  # Connect to the MySQL service
      MYSQL_ROOT_PASSWORD: root  # Match the root password in the db service
    depends_on:
      - db

volumes:
  mysql_data:  # Define a named volume for MySQL data persistence